name: Build and Deploy
on:
  push:
    branches:
      - main  # Define em quais branches esse workflow será executado
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Define o tipo de runner que executará os jobs
    steps:
      - uses: actions/checkout@v2  # Checa o código fonte do repositório

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Define a versão do Node.js

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages  # O branch para onde o conteúdo da build será enviado
          folder: dist  # O diretório que contém os arquivos a serem deployados
          clean: true  # Limpa arquivos antigos no branch de deploy
